services:
  mongo:
    container_name: mongodb
    image: mongo:8.0.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mongoDB:/data/db
    networks:
      - database-network

  dw-postgres:
    container_name: dw-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_DW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DW_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DW_DB}
    volumes:
      - ./postgres-dw-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - database-network

networks:
  database-network:
    name: ${NETWORK}
    external: true