from .stg_aneel_empreendimento_geracao_distribuida import StageAneelEmpreendimentoGeracaoDistribuida
from .stg_aneel_egd_informacoes_tecnicas_eolica import StageAneelEGDInformacoesTecnicasEolica
from .stg_aneel_egd_informacoes_tecnicas_fotovoltaica import StageAneelEGDInformacoesTecnicasFotovoltaica
from .stg_aneel_egd_informacoes_tecnicas_hidreletrica import StageAneelEGDInformacoesTecnicasHidreletrica
from .stg_aneel_egd_informacoes_tecnicas_termeletrica import StageAneelEGDInformacoesTecnicasTermeletrica